### ISSUE TITLE
During

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#22] opened 2019-03-27 10:22 UTC
Where should we zero out during and the variables coming for during? Now it is done in two parts. First during and after are zerod out here in this file. All the variables coming from them are zerod out later in the estimate file. Álmos proposes to zero them out at one place, which is before the regressions are run (so basically in the estimate file). 

https://github.com/korenmiklos/expat-analysis/blob/5a30e6394ce115305e7ae365967388cfa90037b6/variables.do#L141

**Comment by korenmiklos** [comment] 2020-05-25 10:46
Duplicate of #35

**Closed by korenmiklos** 2020-05-25 10:46 UTC
