### ISSUE TITLE
During

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#21] opened 2019-03-12 14:40 UTC
Why zeroing out only during in founder years? Should not we have during* and after* instead? We create some new variables later using during, so it might make sense to decide what to zero out at this point.

https://github.com/korenmiklos/expat-analysis/blob/6eb68242ec1e460feb1cab12ece80a644aeecf68/variables.do#L134

**Comment by korenmiklos** [comment] 2020-05-25 10:45
Duplicate of #35

**Closed by korenmiklos** 2020-05-25 10:45 UTC
Labels: question
